---
output:
  word_document:
    reference_docx: template_word.docx
fontsize: 12pt
geometry: margin=1.5cm
---

```{r echo=FALSE}
opts_knit$set(progress=FALSE, verbose=FALSE)#retire les sorties consoles
#knitr::opts_chunk$set(fig.width=20, fig.height=10) 
knitr::knit_hooks$set(inline = as.character)#évite les erreurs d'écriture des arrondis
opts_chunk$set(echo = FALSE,warning = FALSE,message=FALSE,fig.width =30/2.54,fig.height = 20/2.54)#in inches
```

```{r}
plt_raw_time[["rcp2.6"]]
```

\newpage

```{r}
plt_raw_time[["rcp4.5"]]
```

\newpage

```{r}
plt_raw_time[["rcp8.5"]]
```

\newpage

```{r}
plt_raw_temp[["rcp2.6"]]
```

\newpage

```{r}
plt_raw_temp[["rcp4.5"]]
```

\newpage

```{r}
plt_raw_temp[["rcp8.5"]]
```

\newpage

```{r}
plt_spline_time[["rcp2.6"]]
```

\newpage

```{r}
plt_spline_time[["rcp4.5"]]
```

\newpage

```{r}
plt_spline_time[["rcp8.5"]]
```

\newpage

```{r}
plt_spline_temp[["rcp2.6"]]
```

\newpage

```{r}
plt_spline_temp[["rcp4.5"]]
```

\newpage

```{r}
plt_spline_temp[["rcp8.5"]]
```

\newpage

```{r}
plt_planet_temp
```

\newpage

```{r}
plt_var_rcp2.6
```

\newpage

```{r}
plt_var_rcp4.5
```
\newpage

```{r}
plt_var_rcp8.5
```

\newpage

```{r}
plt_gcm_effect
```

\newpage

```{r}
plt_rcm_effect
```

\newpage

```{r}
plt_bc_effect
```

\newpage

```{r}
plt_hm_effect
```

\newpage

```{r}
plt_var_decomp
```

\newpage

```{r}
plt_change_rcp_time
```

\newpage

```{r}
plt_change_3rcp_temp
```

\newpage

```{r}
plt_change_2rcp_temp
```

