---
output:
  bookdown::word_document2:
    reference_docx: "C:/Users/reverdya/Documents/Docs/1_code/explore/template_word.docx"
    fig_caption: yes
fontsize: 12pt
geometry: margin=1cm
title: "Fiche type de présentation des incertitudes pour EXPLORE 2"
author: "Alix Reverdy, Benoit Hingray (IGE), Guillaume Evin (INRAE)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r echo=FALSE}
opts_knit$set(progress=FALSE, verbose=FALSE)#retire les sorties consoles
#knitr::opts_chunk$set(fig.width=20, fig.height=10) 
knitr::knit_hooks$set(inline = as.character)#évite les erreurs d'écriture des arrondis
opts_chunk$set(echo = FALSE,warning = FALSE,message=FALSE,fig.width =30/2.54,fig.height = 20/2.54)#in inches
```


<!-- Ce document a pour objectif d’illustrer par une série d’exemples les représentations graphiques produites en sortie de l’analyse de la partition d’incertitude entre les différentes chaînes de modélisation. Il a aussi pour but de nourrir la discussion sur les choix graphiques et la compréhension des concepts illustrés sur les figures proposées. Les données utilisées ne doivent pas être interprétées en tant que telles, car elles sont issues d’un **sous-ensemble arbitraire des chaînes de modélisation d’EXPLORE 2 et encore soumises à des modifications futures**. -->

<!-- Le module annuel d’un bassin versant sera utilisé à titre illustratif, mais les représentations proposées sont valables pour d’autres séries temporelles d’indicateurs hydrologiques. De même, on a choisi ici le bassin de la Seine à Poses, mais les représentations graphiques sont transférables à un autre exutoire. -->

<!-- Les analyses (estimation de la moyenne d’ensemble, des effets principaux pour les différents modèles et scénarios et des différentes sources d’incertitudes) sont obtenues avec la méthode QUALYPSO. La méthode permet en particulier de traiter les ensembles de projections incomplets (avec des combinaisons de modèles et expériences manquantes). Elle produit une estimation de la moyenne d’ensemble et des incertitudes proches de celles qui auraient été obtenues avec un ensemble complet. -->

<!-- Les changements décrits sont des changements relatifs du module annuel de débit par rapport à la période de référence 1975-2005 (centrée sur 1990) . -->





\newpage

# Projections brutes et réponses climatiques

<br>

```{r rawtime, fig.cap="Projections brutes du module annuel de débit pour la Seine à Poses et le scénario RCP 8.5. Chaque graphique montre les projections obtenues avec les différents RCMs disponibles pour un même modèle GCM.  Une couleur par RCM. Modèle hydrologique : SIM2. Période : 1972-2098 (période commune des modèles)."}

plt_raw_time
# for reference \@ref(fig:rawtime)
# no underscore in figure label
```

<!-- Chaque panel montre les chroniques pour un modèle GCM et un ou plusieurs modèles RCMs du module annuel de débit de la Seine à Poses. On peut noter l’importante variabilité interannuelle à décennale (variabilité interne) qui “bruite” les tendances. Le module annuel de la Seine à Poses projeté avec le GCM HadGEM2-ES, le RCM REMO et le modèle hydrologique SIM2 pour l’année 2092 s’élève à 1300 m3/s. -->

<!-- **Eclairages :** -->

<!-- 1. Quelque soit la chaîne de simulation, la variabilité temporelle des projections est importante. Pour le cas présent des projections de débit, elle “bruite” de façon importantes les tendances au changement: le module annuel projeté avec la chaîne HadGEM2-ES/REMO/SIM2 à tendance à augmenter sur le siècle mais les fluctuations interannuelles importantes conduisent à des valeurs pour certaines années qui peuvent être moins fortes que celles de la période actuelle. -->

<!-- 2. Les différentes projections obtenues pour un même GCM présentent des chronologies (fluctuations) similaires, ce qui est attendu car les RCMs sont forcés par la même chronologie des conditions atmosphériques “grande échelle”. -->


```{r splinetime, fig.cap="Projections brutes (traits fins) et réponses climatiques correspondantes estimées avec une focntion spline (traits épais) pour le module annuel de la Seine à Poses et le RCP 8.5 entre 1972 et 2098. Chaque graphique montre les projections obtenues avec les différents RCMs disponibles pour un même modèle GCM."}

#plt_spline_time

```

<!-- **A noter :** -->

<!-- 1. La réponse climatique d’une chaîne de simulation pour une période future donnée est la réponse moyenne attendue du système considéré pour cette chaîne aux forçages climatiques (par ex. les gaz à effet de serre). C’est la partie basse fréquence de la chronique des projections brutes. Elle présente donc une évolution lente. -->

<!-- 2. L’écart des projections brutes à la réponse climatique résulte de la variabilité inter-annuelle et des variabilités à plus basse fréquence du système climatique (variabilité interne). Ici, la réponse climatique de chaque chaîne de simulation est extraite des projections brutes à l’aide d’un modèle de spline (c’est donc une réponse climatique estimée). Ces réponses climatiques sont aussi calculées pour les RCP 2.6 et 4.5 (non illustré). -->


<!-- **Eclairages :** -->

<!-- 1. La réponse climatique de la chaîne de modélisation MPI-ESM-LR/REMO présente une tendance à la hausse sur tout le siècle, passant de 500 m3/s en 1990 à plus de 600 m3/s à l'horizon 2100. -->

<!-- 2. Les projections brutes présentent autour de la réponse climatique estimée des fluctuations interannuelles et basses fréquences importantes qui alternativement réduisent cette tendance à la hausse (période 2020-2030 puis 2050-2070) ou l’accentuent (période 2070-2080 puis 2090-2100) pour MPI-ESM-LR/REMO. Ces fluctuations sont dues à la variabilité interne du climat. -->

<!-- 3. Une autre expérience climatique avec cette même chaîne de modélisation aurait produit une réponse climatique similaire, mais aurait produit une chronologie des fluctuations très différente. -->

<!-- 4. Il est donc fondamental de séparer ces 2 composantes (signal / fluctuations) pour avoir une estimation robuste des changements à attendre pour la chaîne considérée.  -->


```{r splinetimerel, fig.cap="Réponses en CHANGEMENT RELATIF climatique correspondantes (toutes les lignes démarrant à 0, référence 1990) pour le module annuel de la Seine à Poses pour le RCP 8.5 entre 1972 et 2098. Chaque graphique montre les réponses en changement climatique obtenues avec les différents RCMs disponibles pour un même modèle GCM. "}

plt_spline_time_rel

```

<!-- **A noter :** -->

<!-- L'utilisation du changement relatif, permet d'obtenir des réponses en changement climatique du module annuel du débit et de pouvoir inter-comparer des bassins avec un débit initial différent. Cette réponse relative est calculée par rapport à la référence de réponse climatique de 1990 (année centrale de la période de référence 1975-2005), extraite de l'estimation par le modèle spline illustrée en Figure \@ref(fig:splinetime). -->


<!-- **Eclairages :** -->

<!-- Ainsi, le changement relatif du module annuel de débit en 2100 par rapport à 1990 est de l'ordre de 25% en réponse climatique, avec des variations du signal brut entre -50 et +100% sur le 21e siècle. -->






\newpage

# Effets principaux des modèles

<br>


```{r eff, fig.cap="Effets principaux des différents a) GCMs, b) RCMs, c) BCs (corrections de biais) et d) HMs (modèles hydrologiques). Les effets BC et HM sont fictifs et donnés à titre illustratif, n'étant pas encore disponibles. Module annuel de la Seine à Poses. Tous les RCP sont considérés."}

grid.arrange(plt_gcm_effect,plt_rcm_effect,plt_bc_effect,ncol=2)

```


<!-- **A noter : ** -->

<!-- 1. L’effet principal d’un modèle donné est la différence entre la réponse moyenne en changement que ce modèle induit par rapport à la réponse moyenne en changement obtenue pour l’ensemble des chaînes de modélisation.  -->

<!-- 2. La somme des effets principaux pour les différents modèles d’un type donné est donc toujours nulle (e.g. la somme des effets principaux obtenus pour les 9 GCMs considérés dans l'ensemble complet EXPLORE 2 sera nulle; la somme des effets principaux des 7 MHs sera nulle, etc…).  -->

<!-- 3. Quel que soit le modèle, son effet principal pour la période de référence (1990) est nul par construction (car la réponse en changement est nulle pour toutes les chaînes de modélisation).  -->

<!-- 4. La réponse en changement d’une chaine de modélisation donnée peut être estimée par la somme de la réponse en changement moyen de l’ensemble complet et des effets principaux de tous les modèles particuliers utilisés pour cette chaîne (e.g. changement moyen + effet IPSL + effet REMO + effet ADAMONT + effet Mordor). -->

<!-- 5. La connaissance des effets principaux des différents modèles permet d’identifier les modèles proches de la moyenne d’ensemble ainsi que les modèles les plus “déviants” et permet éventuellement par la suite d’orienter le choix de chaînes de modélisation spécifiques pour l’étude d’impacts. -->

<!-- **Eclairages :** -->

<!-- 1. Effets principaux des GCMs : A l’horizon 2050 le modèle de l’IPSL a un effet principal d’environ 9%, cela veut dire que les chaînes contenant ce modèle présenteront en moyenne une valeur de changement relatif du module annuel de 9% de plus que la moyenne d’ensemble. A l’inverse, le modèle EC-EARTH a tendance à produire des modules annuels de débit plus faibles que la moyenne dans le futur et le modèle du CNRM est toujours très proche de la moyenne d’ensemble. Une valeur négative d’effet principal ne correspond pas forcément à une baisse de l’indicateur, dans le cas où le changement moyen de l’ensemble est fortement positif. -->

<!-- 2. Effets principaux des RCMs: la réponse en changement de WRF est 40% au-dessus de la réponse en changement moyenne de l’ensemble; la réponse en changement de ALADIN est 20% en-dessous de la réponse en changement moyenne de l’ensemble à l'horizon 2100. -->

```{r change, fig.cap="Changement relatif moyen des différents a) GCMs, b) RCMs, c) BCs (corrections de biais) et d) HMs (modèles hydrologiques). Les changements BC et HM sont fictifs et donnés à titre illustratif, n'étant pas encore disponibles. Module annuel de la Seine à Poses. Tous les RCP sont considérés."}

#grid.arrange(plt_gcm_change,plt_rcm_change,plt_bc_change,ncol=2)

```

<!-- **A noter : ** -->

<!-- On représente ici non pas les effets principaux, mais le changement relatif moyen de chaque modèle. Soit la somme de son effet principal et du changement moyen de l'ensemble inter-modèles. -->

<!-- **Eclairages :** -->

<!-- A l’horizon 2050 le modèle de l’IPSL a un changement moyen d'environ +20%, alors que EC-EARTH montre un changement moyen de seulement 3%. On note bien que malgré un effet principal négatif (Figure \@ref(fig:eff)) EC-EARTH montre un changement moyen positif. Il produit des changements plus faibles que la moyenne d'ensemble, mais néanmoins positifs. -->






\newpage

# Signal de changement, incertitude et sources d'incertitude

<br>

```{r bilan,dpi=300, fig.cap="toto",fig.height = 20/2.54*1.8,fig.asp=1}

plt_bilan

```

```{r bxplt,dpi=300, fig.cap="toto"}

plt_bxplt

```


\newpage

# Représentations cartographiques

```{r mapquanthoriz,dpi=300, fig.cap="Carte du changement relatif du module annuel de débit pour la France métropolitaine en RCP 8.5, par rapport à la référence 1990, à 3 horizons temporels: 2030, 2050 et 2085 (en lignes). En colonnes sont donnés la moyenne d'ensemble et l'intervalle de confiance 5/95% obtenus avec la méthode QUALYPSO. Cette intervalle de confiance prend en compte la dispersion entre les GCMS, les RCM et la variabilité résiduelle. Points à l'exutoire."}

map_quant_horiz

```


<!-- **Eclairages : ** -->

<!-- On observe une variation spatiale assez importante du signal de changement relatif du module annuel à l'échelle du territoire, avec des valeurs moyennes comprises entre environ entre -30% et +50% suivant la région, mais des transitions spatiales assez régulières. L'intervalle de confiance produit des valeurs d'environ -50% au Sud jusqu'à +100% au Nord en 2085. Plus l'horizon temporel est distant, plus le changement (positif ou négatif) est marqué et l'incertitude est grande. -->


```{r mapiv,dpi=300,fig.width =15/2.54,fig.height = 10/2.54,fig.cap="Carte de l'incertitude (écart-type) liée à la variabilité interne du module annuel de débit pour la France métropolitaine. Points à l'exutoire."}

map_iv

```


```{r mappart,dpi=300,fig.width =30/2.54,fig.height = 22/2.54, fig.cap="Carte de la partition de variance pour la France métropolitaine. Points à l'exutoire."}

map_part

```

<!-- **Eclairages : ** -->

<!-- 1. La figure précédente montrait l'incertitude sur le signal de réponse au changement climatique, sans prise en compte de la variabilité interne du système climatique. Pour référence l'incertitude (écart-type) de cette variabilité est donné ici, afin de mettre en perspective signaux de changements et variabilité interne. -->

<!-- 2. Cette incertitude est comprise entre 30 et 80% environ, avec un maximum sur le pourtour Méditerranéen. -->



```{r mapgcmeff,dpi=300,fig.width =30/2.54,fig.height = 13.3/2.54, fig.cap="Carte des effets principaux des GCMs pour le module annuel de débit sur la France métropolitaine en 2050, par rapport à la référence 1990. Points à l'exutoire."}

#map_gcmeff

```

<!-- **Eclairages : ** -->

<!-- 1. On représente cette fois les effets principaux de chaque GCM. Il est ainsi possible de voir que le modèle du CNRM a un effet principal très faible (sauf sur les Pyrénées) et produit donc des valeurs de module annuel très proches de la moyenne d'ensemble multi-modèles. A l'inverse, EC-EARTH produit des valeurs plus faibles que la moyenne dans le Nord. La dispersion des GCMs est très peu marquée sur un bande Nord-Ouest à Sud-Est où tous les GCMs ont des effets principaux très faibles. -->

<!-- 2. En chaque point la somme des effets est nulle par hypothèse de construction. -->


```{r maprcmeff,dpi=300, fig.cap="Carte des effets principaux des RCMs pour le module annuel de débit sur la France métropolitaine en 2050, par rapport à la référence 1990. Points à l'exutoire."}

#map_rcmeff

```


<!-- **Eclairages : ** -->

<!-- On représente cette fois les effets principaux de chaque RCM. Le résultat marquant ici est une illustration de l'utilité d'étudier les effets principaux. On peut voir qu'avec notre sous-ensemble arbitraire d'EXPLORE 2 le RCM WRF381P a un effet principal particulièrement marqué sur le bassin Parisien. Il produit donc des modules annuels de débit environ 40% plus élevés que la moyenne d'ensemble. On a donc pu mettre en évidence (pour cet exemple arbitraire) un maillon de la chaîne de modélisation particulièrement intéressant à étudier en détail si l'intérêt de l'utilisateur se porte sur les fortes augmentations ou à retirer si ce dernier se porte sur des scénarios plus médians. -->

```{r mapgcmch,dpi=300,fig.width =30/2.54,fig.height = 13.3/2.54, fig.cap="Carte des changements relatifs pour le module annuel de débit en fonction du GCM sur la France métropolitaine en 2050, par rapport à la référence 1990. Les valeurs sont les moyennes d'ensemble complet pour un GCM donné. Points à l'exutoire."}

map_gcmchang

```

<!-- **Eclairages : ** -->

<!-- 1. La représentation des effets principaux a l'avantage d'isoler facilement les modèles les plus divergents, mais peut être trompeuse, ne prenant pas en compte le signe du changement moyen. On a donc représenté ici le changement moyen de chaque GCM. -->

<!-- 2. Cette figure permet de mettre en évidence que si le changement moyen produit par EC-EARTH est assez faible et continu sur toute la France, il existe un fort contraste Nord-Sud sur les changements relatifs prédits par le modèle de l'IPSL, avec une diminution dans la zone Pyrénéenne et une augmentation dans le Nord. -->


```{r maprcmch,dpi=300, fig.cap="Carte des changements relatifs pour le module annuel de débit en fonction du RCM sur la France métropolitaine en 2050, par rapport à la référence 1990. Les valeurs sont les moyennes d'ensemble complet pour un RCM donné. Points à l'exutoire."}

#map_rcmchang

```

<!-- **Eclairages : ** -->

<!-- On retrouve le changement positif marqué de WRF381P. Mais cette nouvelle représentation permet d'illustrer que même si les autres modèles présentent des effets principaux relativement négatifs, le changement associé peut être positif (RACMO22E dans le Nord par exemple). -->